#!/usr/bin/python3

# Copyright (C) 2026 pmdtechnologies gmbh
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS 
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE 
# GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY 
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import os
import time 
import numpy as np
import sys

import o3py

def calc_rgb(value, minimum, maximum):
    """
    Calculate RGB values.
    :param value: Value to translate to RGB
    :param minimum: Minimum value
    :param maximum: Maximum value
    :return: RGB values
    """
    if isinstance(value, np.ndarray):
        value = value.astype(float)
    else:
        value = float(value)
    ratio = 2 * (value - minimum) / (maximum - minimum)
    b = np.maximum(0, 255 * (1 - ratio)).astype(int)
    r = np.maximum(0, 255 * (ratio - 1)).astype(int)
    g = 255 - b - r
    return r, g, b


def write_ply_file(file_path: str | os.PathLike, xyz: np.ndarray, rgb: np.ndarray):
    """
    Write the XYZ data and the RGB / amplitude into a ply file.
    :param file_path: Full path for writing the file
    :param xyz: XYZ-Coordinates in m
    :param rgb: RGB values / Amplitude value for each XYZ in DN
    :return:
    """
    if not isinstance(file_path, (str, os.PathLike)):
        raise TypeError(f"Unsupported file path: {type(file_path)}. Must be str, os.PathLike.")

    if not isinstance(xyz, np.ndarray):
        raise TypeError("XYZ must be a numpy array!")
    if not isinstance(rgb, np.ndarray):
        raise TypeError("RGB must be a numpy array!")

    # Normalize/reshape pointcloud input:
    # o3py pointcloud is typically (H, W, 4) containing x,y,z,c per pixel (or sometimes flattened).
    # We generate a 4D "image" representation with shape (1, H, W, 4) and use only x,y,z for PLY.
    if xyz.shape[-1] == 4:
        xyzc = xyz  # x,y,z,c (per pixel)
        xyz = xyzc[..., :3]  # keep only x,y,z for writing
        xyz_4d = xyzc[np.newaxis, ...]  # (1,H,W,4)
    elif xyz.shape[-1] == 3:
        xyz_4d = xyz[np.newaxis, ...]  # (1,H,W,3)
    else:
        raise ValueError("XYZ last dimension must be 3 (x,y,z) or 4 (x,y,z,c)!")

    if xyz.shape[-1] != 3:
        raise ValueError("XYZ last dimension must be 3!")
    x = xyz[..., 0].ravel()
    y = xyz[..., 1].ravel()
    z = xyz[..., 2].ravel()

    if rgb.size == x.size:
        r, g, b = calc_rgb(rgb.ravel(), np.min(rgb), np.max(rgb))
    elif rgb.size == 3 * x.size:
        if rgb.shape[-1] != 3:
            raise ValueError("RGB last dimension must be 3!")
        r = rgb[..., 0].ravel()
        g = rgb[..., 1].ravel()
        b = rgb[..., 2].ravel()
    else:
        raise ValueError("RGB size does not match XYZ size!")

    with open(file_path, "wt") as f:
        # Write the header
        f.write("ply\n")
        f.write("format ascii 1.0\n")
        f.write("comment Generated by pmdtechnologies gmbh, www.pmdtec.com\n")
        f.write(f"element vertex {x.size}\n")
        f.write("property float x\n")
        f.write("property float y\n")
        f.write("property float z\n")
        f.write("property uchar red\n")
        f.write("property uchar green\n")
        f.write("property uchar blue\n")
        f.write("element face 0\n")
        f.write("property list uchar int vertex_index\n")
        f.write("end_header\n")
        # Write all the pixels
        for xi, yi, zi, ri, gi, bi in zip(x, y, z, r, g, b):
            f.write(f"{xi} {yi} {zi} {ri} {gi} {bi}\n")

# create, initialize and start the pipeline
pipe = o3py.Pipeline()
pipe.init()
pipe.start()

start = time.time()
loop_time = 10

current_file = os.path.abspath(__file__)
current_dir = os.path.dirname(current_file)

while time.time() - start < loop_time:
    try:
        frames = pipe.waitForFrames() # get frames

        # Infrared
        ir = frames.getInfraredFrame()
        w = ir.getWidth()
        h = ir.getHeight()
        irData = ir.getData()
        if irData.size == 0:
            print("No IR data")
            continue

        # POINTCLOUD
        pc = frames.getPointCloudFrame()
        w = pc.getWidth()
        h = pc.getHeight()
        pcData = pc.getData()
        if pcData.size == 0:
            print("No Pointcloud data")
            continue

        write_ply_file(os.path.join(current_dir, "pointcloud_frame" + ".ply"), pcData, irData)
        print("Saved Pointcloud in ", current_dir)
        sys.exit()

    except Exception as e:
        print(f"Error grabbing frame: {e}")