# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _o3py
else:
    import _o3py

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SHARED_PTR_DISOWN = _o3py.SHARED_PTR_DISOWN
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _o3py.delete_SwigPyIterator

    def value(self):
        return _o3py.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _o3py.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _o3py.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _o3py.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _o3py.SwigPyIterator_equal(self, x)

    def copy(self):
        return _o3py.SwigPyIterator_copy(self)

    def next(self):
        return _o3py.SwigPyIterator_next(self)

    def __next__(self):
        return _o3py.SwigPyIterator___next__(self)

    def previous(self):
        return _o3py.SwigPyIterator_previous(self)

    def advance(self, n):
        return _o3py.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _o3py.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _o3py.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _o3py.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _o3py.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _o3py.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _o3py.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _o3py:
_o3py.SwigPyIterator_swigregister(SwigPyIterator)
class VectorStream(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _o3py.VectorStream_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _o3py.VectorStream___nonzero__(self)

    def __bool__(self):
        return _o3py.VectorStream___bool__(self)

    def __len__(self):
        return _o3py.VectorStream___len__(self)

    def __getslice__(self, i, j):
        return _o3py.VectorStream___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _o3py.VectorStream___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _o3py.VectorStream___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _o3py.VectorStream___delitem__(self, *args)

    def __getitem__(self, *args):
        return _o3py.VectorStream___getitem__(self, *args)

    def __setitem__(self, *args):
        return _o3py.VectorStream___setitem__(self, *args)

    def pop(self):
        return _o3py.VectorStream_pop(self)

    def append(self, x):
        return _o3py.VectorStream_append(self, x)

    def empty(self):
        return _o3py.VectorStream_empty(self)

    def size(self):
        return _o3py.VectorStream_size(self)

    def swap(self, v):
        return _o3py.VectorStream_swap(self, v)

    def begin(self):
        return _o3py.VectorStream_begin(self)

    def end(self):
        return _o3py.VectorStream_end(self)

    def rbegin(self):
        return _o3py.VectorStream_rbegin(self)

    def rend(self):
        return _o3py.VectorStream_rend(self)

    def clear(self):
        return _o3py.VectorStream_clear(self)

    def get_allocator(self):
        return _o3py.VectorStream_get_allocator(self)

    def pop_back(self):
        return _o3py.VectorStream_pop_back(self)

    def erase(self, *args):
        return _o3py.VectorStream_erase(self, *args)

    def __init__(self, *args):
        _o3py.VectorStream_swiginit(self, _o3py.new_VectorStream(*args))

    def push_back(self, x):
        return _o3py.VectorStream_push_back(self, x)

    def front(self):
        return _o3py.VectorStream_front(self)

    def back(self):
        return _o3py.VectorStream_back(self)

    def assign(self, n, x):
        return _o3py.VectorStream_assign(self, n, x)

    def resize(self, *args):
        return _o3py.VectorStream_resize(self, *args)

    def insert(self, *args):
        return _o3py.VectorStream_insert(self, *args)

    def reserve(self, n):
        return _o3py.VectorStream_reserve(self, n)

    def capacity(self):
        return _o3py.VectorStream_capacity(self)
    __swig_destroy__ = _o3py.delete_VectorStream

# Register VectorStream in _o3py:
_o3py.VectorStream_swigregister(VectorStream)
class VectorString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _o3py.VectorString_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _o3py.VectorString___nonzero__(self)

    def __bool__(self):
        return _o3py.VectorString___bool__(self)

    def __len__(self):
        return _o3py.VectorString___len__(self)

    def __getslice__(self, i, j):
        return _o3py.VectorString___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _o3py.VectorString___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _o3py.VectorString___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _o3py.VectorString___delitem__(self, *args)

    def __getitem__(self, *args):
        return _o3py.VectorString___getitem__(self, *args)

    def __setitem__(self, *args):
        return _o3py.VectorString___setitem__(self, *args)

    def pop(self):
        return _o3py.VectorString_pop(self)

    def append(self, x):
        return _o3py.VectorString_append(self, x)

    def empty(self):
        return _o3py.VectorString_empty(self)

    def size(self):
        return _o3py.VectorString_size(self)

    def swap(self, v):
        return _o3py.VectorString_swap(self, v)

    def begin(self):
        return _o3py.VectorString_begin(self)

    def end(self):
        return _o3py.VectorString_end(self)

    def rbegin(self):
        return _o3py.VectorString_rbegin(self)

    def rend(self):
        return _o3py.VectorString_rend(self)

    def clear(self):
        return _o3py.VectorString_clear(self)

    def get_allocator(self):
        return _o3py.VectorString_get_allocator(self)

    def pop_back(self):
        return _o3py.VectorString_pop_back(self)

    def erase(self, *args):
        return _o3py.VectorString_erase(self, *args)

    def __init__(self, *args):
        _o3py.VectorString_swiginit(self, _o3py.new_VectorString(*args))

    def push_back(self, x):
        return _o3py.VectorString_push_back(self, x)

    def front(self):
        return _o3py.VectorString_front(self)

    def back(self):
        return _o3py.VectorString_back(self)

    def assign(self, n, x):
        return _o3py.VectorString_assign(self, n, x)

    def resize(self, *args):
        return _o3py.VectorString_resize(self, *args)

    def insert(self, *args):
        return _o3py.VectorString_insert(self, *args)

    def reserve(self, n):
        return _o3py.VectorString_reserve(self, n)

    def capacity(self):
        return _o3py.VectorString_capacity(self)
    __swig_destroy__ = _o3py.delete_VectorString

# Register VectorString in _o3py:
_o3py.VectorString_swigregister(VectorString)
class VectorFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _o3py.VectorFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _o3py.VectorFloat___nonzero__(self)

    def __bool__(self):
        return _o3py.VectorFloat___bool__(self)

    def __len__(self):
        return _o3py.VectorFloat___len__(self)

    def __getslice__(self, i, j):
        return _o3py.VectorFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _o3py.VectorFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _o3py.VectorFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _o3py.VectorFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _o3py.VectorFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _o3py.VectorFloat___setitem__(self, *args)

    def pop(self):
        return _o3py.VectorFloat_pop(self)

    def append(self, x):
        return _o3py.VectorFloat_append(self, x)

    def empty(self):
        return _o3py.VectorFloat_empty(self)

    def size(self):
        return _o3py.VectorFloat_size(self)

    def swap(self, v):
        return _o3py.VectorFloat_swap(self, v)

    def begin(self):
        return _o3py.VectorFloat_begin(self)

    def end(self):
        return _o3py.VectorFloat_end(self)

    def rbegin(self):
        return _o3py.VectorFloat_rbegin(self)

    def rend(self):
        return _o3py.VectorFloat_rend(self)

    def clear(self):
        return _o3py.VectorFloat_clear(self)

    def get_allocator(self):
        return _o3py.VectorFloat_get_allocator(self)

    def pop_back(self):
        return _o3py.VectorFloat_pop_back(self)

    def erase(self, *args):
        return _o3py.VectorFloat_erase(self, *args)

    def __init__(self, *args):
        _o3py.VectorFloat_swiginit(self, _o3py.new_VectorFloat(*args))

    def push_back(self, x):
        return _o3py.VectorFloat_push_back(self, x)

    def front(self):
        return _o3py.VectorFloat_front(self)

    def back(self):
        return _o3py.VectorFloat_back(self)

    def assign(self, n, x):
        return _o3py.VectorFloat_assign(self, n, x)

    def resize(self, *args):
        return _o3py.VectorFloat_resize(self, *args)

    def insert(self, *args):
        return _o3py.VectorFloat_insert(self, *args)

    def reserve(self, n):
        return _o3py.VectorFloat_reserve(self, n)

    def capacity(self):
        return _o3py.VectorFloat_capacity(self)
    __swig_destroy__ = _o3py.delete_VectorFloat

# Register VectorFloat in _o3py:
_o3py.VectorFloat_swigregister(VectorFloat)
class VectorVectorFloat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _o3py.VectorVectorFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _o3py.VectorVectorFloat___nonzero__(self)

    def __bool__(self):
        return _o3py.VectorVectorFloat___bool__(self)

    def __len__(self):
        return _o3py.VectorVectorFloat___len__(self)

    def __getslice__(self, i, j):
        return _o3py.VectorVectorFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _o3py.VectorVectorFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _o3py.VectorVectorFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _o3py.VectorVectorFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _o3py.VectorVectorFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _o3py.VectorVectorFloat___setitem__(self, *args)

    def pop(self):
        return _o3py.VectorVectorFloat_pop(self)

    def append(self, x):
        return _o3py.VectorVectorFloat_append(self, x)

    def empty(self):
        return _o3py.VectorVectorFloat_empty(self)

    def size(self):
        return _o3py.VectorVectorFloat_size(self)

    def swap(self, v):
        return _o3py.VectorVectorFloat_swap(self, v)

    def begin(self):
        return _o3py.VectorVectorFloat_begin(self)

    def end(self):
        return _o3py.VectorVectorFloat_end(self)

    def rbegin(self):
        return _o3py.VectorVectorFloat_rbegin(self)

    def rend(self):
        return _o3py.VectorVectorFloat_rend(self)

    def clear(self):
        return _o3py.VectorVectorFloat_clear(self)

    def get_allocator(self):
        return _o3py.VectorVectorFloat_get_allocator(self)

    def pop_back(self):
        return _o3py.VectorVectorFloat_pop_back(self)

    def erase(self, *args):
        return _o3py.VectorVectorFloat_erase(self, *args)

    def __init__(self, *args):
        _o3py.VectorVectorFloat_swiginit(self, _o3py.new_VectorVectorFloat(*args))

    def push_back(self, x):
        return _o3py.VectorVectorFloat_push_back(self, x)

    def front(self):
        return _o3py.VectorVectorFloat_front(self)

    def back(self):
        return _o3py.VectorVectorFloat_back(self)

    def assign(self, n, x):
        return _o3py.VectorVectorFloat_assign(self, n, x)

    def resize(self, *args):
        return _o3py.VectorVectorFloat_resize(self, *args)

    def insert(self, *args):
        return _o3py.VectorVectorFloat_insert(self, *args)

    def reserve(self, n):
        return _o3py.VectorVectorFloat_reserve(self, n)

    def capacity(self):
        return _o3py.VectorVectorFloat_capacity(self)
    __swig_destroy__ = _o3py.delete_VectorVectorFloat

# Register VectorVectorFloat in _o3py:
_o3py.VectorVectorFloat_swigregister(VectorVectorFloat)
class VectorUint16t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _o3py.VectorUint16t_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _o3py.VectorUint16t___nonzero__(self)

    def __bool__(self):
        return _o3py.VectorUint16t___bool__(self)

    def __len__(self):
        return _o3py.VectorUint16t___len__(self)

    def __getslice__(self, i, j):
        return _o3py.VectorUint16t___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _o3py.VectorUint16t___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _o3py.VectorUint16t___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _o3py.VectorUint16t___delitem__(self, *args)

    def __getitem__(self, *args):
        return _o3py.VectorUint16t___getitem__(self, *args)

    def __setitem__(self, *args):
        return _o3py.VectorUint16t___setitem__(self, *args)

    def pop(self):
        return _o3py.VectorUint16t_pop(self)

    def append(self, x):
        return _o3py.VectorUint16t_append(self, x)

    def empty(self):
        return _o3py.VectorUint16t_empty(self)

    def size(self):
        return _o3py.VectorUint16t_size(self)

    def swap(self, v):
        return _o3py.VectorUint16t_swap(self, v)

    def begin(self):
        return _o3py.VectorUint16t_begin(self)

    def end(self):
        return _o3py.VectorUint16t_end(self)

    def rbegin(self):
        return _o3py.VectorUint16t_rbegin(self)

    def rend(self):
        return _o3py.VectorUint16t_rend(self)

    def clear(self):
        return _o3py.VectorUint16t_clear(self)

    def get_allocator(self):
        return _o3py.VectorUint16t_get_allocator(self)

    def pop_back(self):
        return _o3py.VectorUint16t_pop_back(self)

    def erase(self, *args):
        return _o3py.VectorUint16t_erase(self, *args)

    def __init__(self, *args):
        _o3py.VectorUint16t_swiginit(self, _o3py.new_VectorUint16t(*args))

    def push_back(self, x):
        return _o3py.VectorUint16t_push_back(self, x)

    def front(self):
        return _o3py.VectorUint16t_front(self)

    def back(self):
        return _o3py.VectorUint16t_back(self)

    def assign(self, n, x):
        return _o3py.VectorUint16t_assign(self, n, x)

    def resize(self, *args):
        return _o3py.VectorUint16t_resize(self, *args)

    def insert(self, *args):
        return _o3py.VectorUint16t_insert(self, *args)

    def reserve(self, n):
        return _o3py.VectorUint16t_reserve(self, n)

    def capacity(self):
        return _o3py.VectorUint16t_capacity(self)
    __swig_destroy__ = _o3py.delete_VectorUint16t

# Register VectorUint16t in _o3py:
_o3py.VectorUint16t_swigregister(VectorUint16t)
class VectorUint8t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _o3py.VectorUint8t_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _o3py.VectorUint8t___nonzero__(self)

    def __bool__(self):
        return _o3py.VectorUint8t___bool__(self)

    def __len__(self):
        return _o3py.VectorUint8t___len__(self)

    def __getslice__(self, i, j):
        return _o3py.VectorUint8t___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _o3py.VectorUint8t___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _o3py.VectorUint8t___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _o3py.VectorUint8t___delitem__(self, *args)

    def __getitem__(self, *args):
        return _o3py.VectorUint8t___getitem__(self, *args)

    def __setitem__(self, *args):
        return _o3py.VectorUint8t___setitem__(self, *args)

    def pop(self):
        return _o3py.VectorUint8t_pop(self)

    def append(self, x):
        return _o3py.VectorUint8t_append(self, x)

    def empty(self):
        return _o3py.VectorUint8t_empty(self)

    def size(self):
        return _o3py.VectorUint8t_size(self)

    def swap(self, v):
        return _o3py.VectorUint8t_swap(self, v)

    def begin(self):
        return _o3py.VectorUint8t_begin(self)

    def end(self):
        return _o3py.VectorUint8t_end(self)

    def rbegin(self):
        return _o3py.VectorUint8t_rbegin(self)

    def rend(self):
        return _o3py.VectorUint8t_rend(self)

    def clear(self):
        return _o3py.VectorUint8t_clear(self)

    def get_allocator(self):
        return _o3py.VectorUint8t_get_allocator(self)

    def pop_back(self):
        return _o3py.VectorUint8t_pop_back(self)

    def erase(self, *args):
        return _o3py.VectorUint8t_erase(self, *args)

    def __init__(self, *args):
        _o3py.VectorUint8t_swiginit(self, _o3py.new_VectorUint8t(*args))

    def push_back(self, x):
        return _o3py.VectorUint8t_push_back(self, x)

    def front(self):
        return _o3py.VectorUint8t_front(self)

    def back(self):
        return _o3py.VectorUint8t_back(self)

    def assign(self, n, x):
        return _o3py.VectorUint8t_assign(self, n, x)

    def resize(self, *args):
        return _o3py.VectorUint8t_resize(self, *args)

    def insert(self, *args):
        return _o3py.VectorUint8t_insert(self, *args)

    def reserve(self, n):
        return _o3py.VectorUint8t_reserve(self, n)

    def capacity(self):
        return _o3py.VectorUint8t_capacity(self)
    __swig_destroy__ = _o3py.delete_VectorUint8t

# Register VectorUint8t in _o3py:
_o3py.VectorUint8t_swigregister(VectorUint8t)

def getApiVersion():
    return _o3py.getApiVersion()

def getApiVersionString():
    return _o3py.getApiVersionString()
RESERVED = _o3py.RESERVED
PIN_HOLE = _o3py.PIN_HOLE
PIN_HOLE_REAL = _o3py.PIN_HOLE_REAL
PIN_HOLE_VIRTUAL = _o3py.PIN_HOLE_VIRTUAL
FISH_EYE = _o3py.FISH_EYE
O3P_METADATA_TIMESTAMP = _o3py.O3P_METADATA_TIMESTAMP
O3P_METADATA_FRAME_NUMBER = _o3py.O3P_METADATA_FRAME_NUMBER
O3P_METADATA_EXPOSURE_TIME_1 = _o3py.O3P_METADATA_EXPOSURE_TIME_1
O3P_METADATA_EXPOSURE_TIME_2 = _o3py.O3P_METADATA_EXPOSURE_TIME_2
O3P_METADATA_TEMPERATURE = _o3py.O3P_METADATA_TEMPERATURE
O3P_METADATA_ANALOG_GAIN = _o3py.O3P_METADATA_ANALOG_GAIN
O3P_METADATA_WHITE_BALANCE = _o3py.O3P_METADATA_WHITE_BALANCE
class MetadataInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    type = property(_o3py.MetadataInfo_type_get, _o3py.MetadataInfo_type_set)
    size = property(_o3py.MetadataInfo_size_get, _o3py.MetadataInfo_size_set)
    name = property(_o3py.MetadataInfo_name_get, _o3py.MetadataInfo_name_set)

    def __init__(self):
        _o3py.MetadataInfo_swiginit(self, _o3py.new_MetadataInfo())
    __swig_destroy__ = _o3py.delete_MetadataInfo

# Register MetadataInfo in _o3py:
_o3py.MetadataInfo_swigregister(MetadataInfo)
class MetadataField(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    type = property(_o3py.MetadataField_type_get, _o3py.MetadataField_type_set)
    offset = property(_o3py.MetadataField_offset_get, _o3py.MetadataField_offset_set)

    def __init__(self):
        _o3py.MetadataField_swiginit(self, _o3py.new_MetadataField())
    __swig_destroy__ = _o3py.delete_MetadataField

# Register MetadataField in _o3py:
_o3py.MetadataField_swigregister(MetadataField)
cvar = _o3py.cvar
METADATA_INFO = cvar.METADATA_INFO


def getMetadataLayoutFromBuffer(buffer, len):
    return _o3py.getMetadataLayoutFromBuffer(buffer, len)

def getMetadataLayout(types):
    return _o3py.getMetadataLayout(types)

def applyMetadataLayoutToBuffer(buffer, layout):
    return _o3py.applyMetadataLayoutToBuffer(buffer, layout)

def calculateMetadataBufferSize(metadataTypes):
    return _o3py.calculateMetadataBufferSize(metadataTypes)
O3P_STREAM_ANY = _o3py.O3P_STREAM_ANY
O3P_STREAM_DEPTH = _o3py.O3P_STREAM_DEPTH
O3P_STREAM_COLOR = _o3py.O3P_STREAM_COLOR
O3P_STREAM_INFRARED = _o3py.O3P_STREAM_INFRARED
O3P_STREAM_IMU = _o3py.O3P_STREAM_IMU
O3P_STREAM_PLUGIN = _o3py.O3P_STREAM_PLUGIN
O3P_STREAM_POSE = _o3py.O3P_STREAM_POSE
O3P_STREAM_CONFIDENCE = _o3py.O3P_STREAM_CONFIDENCE
O3P_STREAM_ULTRASONIC = _o3py.O3P_STREAM_ULTRASONIC
O3P_STREAM_COUNT = _o3py.O3P_STREAM_COUNT

def streamType2String(type):
    return _o3py.streamType2String(type)
class Intrinsics(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ppx = property(_o3py.Intrinsics_ppx_get, _o3py.Intrinsics_ppx_set)
    ppy = property(_o3py.Intrinsics_ppy_get, _o3py.Intrinsics_ppy_set)
    fx = property(_o3py.Intrinsics_fx_get, _o3py.Intrinsics_fx_set)
    fy = property(_o3py.Intrinsics_fy_get, _o3py.Intrinsics_fy_set)
    model = property(_o3py.Intrinsics_model_get, _o3py.Intrinsics_model_set)
    coeffs = property(_o3py.Intrinsics_coeffs_get, _o3py.Intrinsics_coeffs_set)

    def getCoeffs(self):
        return _o3py.Intrinsics_getCoeffs(self)

    def __init__(self):
        _o3py.Intrinsics_swiginit(self, _o3py.new_Intrinsics())
    __swig_destroy__ = _o3py.delete_Intrinsics

# Register Intrinsics in _o3py:
_o3py.Intrinsics_swigregister(Intrinsics)
class Extrinsics(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _o3py.Extrinsics_swiginit(self, _o3py.new_Extrinsics())
    rotation = property(_o3py.Extrinsics_rotation_get, _o3py.Extrinsics_rotation_set)
    translation = property(_o3py.Extrinsics_translation_get, _o3py.Extrinsics_translation_set)

    def getRotation(self):
        return _o3py.Extrinsics_getRotation(self)

    def getTranslation(self):
        return _o3py.Extrinsics_getTranslation(self)
    __swig_destroy__ = _o3py.delete_Extrinsics

# Register Extrinsics in _o3py:
_o3py.Extrinsics_swigregister(Extrinsics)
MAX_COMPOSITE_FRAME_BUFFERS = _o3py.MAX_COMPOSITE_FRAME_BUFFERS
class CompositeBufferConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    type = property(_o3py.CompositeBufferConfig_type_get, _o3py.CompositeBufferConfig_type_set)
    byteOffset = property(_o3py.CompositeBufferConfig_byteOffset_get, _o3py.CompositeBufferConfig_byteOffset_set)
    byteSize = property(_o3py.CompositeBufferConfig_byteSize_get, _o3py.CompositeBufferConfig_byteSize_set)
    metadataSize = property(_o3py.CompositeBufferConfig_metadataSize_get, _o3py.CompositeBufferConfig_metadataSize_set)
    width = property(_o3py.CompositeBufferConfig_width_get, _o3py.CompositeBufferConfig_width_set)
    height = property(_o3py.CompositeBufferConfig_height_get, _o3py.CompositeBufferConfig_height_set)

    def __init__(self):
        _o3py.CompositeBufferConfig_swiginit(self, _o3py.new_CompositeBufferConfig())
    __swig_destroy__ = _o3py.delete_CompositeBufferConfig

# Register CompositeBufferConfig in _o3py:
_o3py.CompositeBufferConfig_swigregister(CompositeBufferConfig)
class CompositeFrameConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    numBuffers = property(_o3py.CompositeFrameConfig_numBuffers_get, _o3py.CompositeFrameConfig_numBuffers_set)
    bufferConfigs = property(_o3py.CompositeFrameConfig_bufferConfigs_get, _o3py.CompositeFrameConfig_bufferConfigs_set)

    def __init__(self):
        _o3py.CompositeFrameConfig_swiginit(self, _o3py.new_CompositeFrameConfig())
    __swig_destroy__ = _o3py.delete_CompositeFrameConfig

# Register CompositeFrameConfig in _o3py:
_o3py.CompositeFrameConfig_swigregister(CompositeFrameConfig)
class Guid(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    data1 = property(_o3py.Guid_data1_get, _o3py.Guid_data1_set)
    data2 = property(_o3py.Guid_data2_get, _o3py.Guid_data2_set)
    data3 = property(_o3py.Guid_data3_get, _o3py.Guid_data3_set)
    data4 = property(_o3py.Guid_data4_get, _o3py.Guid_data4_set)

    def __init__(self):
        _o3py.Guid_swiginit(self, _o3py.new_Guid())
    __swig_destroy__ = _o3py.delete_Guid

# Register Guid in _o3py:
_o3py.Guid_swigregister(Guid)
LENS_PARAMETERS = _o3py.LENS_PARAMETERS
MESSAGE_PACKET = _o3py.MESSAGE_PACKET
class UsbDisconnectedException(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, message):
        _o3py.UsbDisconnectedException_swiginit(self, _o3py.new_UsbDisconnectedException(message))
    __swig_destroy__ = _o3py.delete_UsbDisconnectedException

# Register UsbDisconnectedException in _o3py:
_o3py.UsbDisconnectedException_swigregister(UsbDisconnectedException)
class BagFileEndReachedWarning(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, message):
        _o3py.BagFileEndReachedWarning_swiginit(self, _o3py.new_BagFileEndReachedWarning(message))

# Register BagFileEndReachedWarning in _o3py:
_o3py.BagFileEndReachedWarning_swigregister(BagFileEndReachedWarning)
class DeviceInfoV1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    serialNumber = property(_o3py.DeviceInfoV1_serialNumber_get, _o3py.DeviceInfoV1_serialNumber_set)
    cpuId = property(_o3py.DeviceInfoV1_cpuId_get, _o3py.DeviceInfoV1_cpuId_set)
    cpuCode = property(_o3py.DeviceInfoV1_cpuCode_get, _o3py.DeviceInfoV1_cpuCode_set)
    cpuVersion = property(_o3py.DeviceInfoV1_cpuVersion_get, _o3py.DeviceInfoV1_cpuVersion_set)

    def __init__(self):
        _o3py.DeviceInfoV1_swiginit(self, _o3py.new_DeviceInfoV1())
    __swig_destroy__ = _o3py.delete_DeviceInfoV1

# Register DeviceInfoV1 in _o3py:
_o3py.DeviceInfoV1_swigregister(DeviceInfoV1)
class DeviceInfoV2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    serialNumber = property(_o3py.DeviceInfoV2_serialNumber_get, _o3py.DeviceInfoV2_serialNumber_set)
    cpuId = property(_o3py.DeviceInfoV2_cpuId_get, _o3py.DeviceInfoV2_cpuId_set)
    cpuCode = property(_o3py.DeviceInfoV2_cpuCode_get, _o3py.DeviceInfoV2_cpuCode_set)
    cpuVersion = property(_o3py.DeviceInfoV2_cpuVersion_get, _o3py.DeviceInfoV2_cpuVersion_set)
    fwVersion = property(_o3py.DeviceInfoV2_fwVersion_get, _o3py.DeviceInfoV2_fwVersion_set)
    fwVersionBuild = property(_o3py.DeviceInfoV2_fwVersionBuild_get, _o3py.DeviceInfoV2_fwVersionBuild_set)
    fwVersionDate = property(_o3py.DeviceInfoV2_fwVersionDate_get, _o3py.DeviceInfoV2_fwVersionDate_set)
    fwVersionHash = property(_o3py.DeviceInfoV2_fwVersionHash_get, _o3py.DeviceInfoV2_fwVersionHash_set)
    fwVersionCustomer = property(_o3py.DeviceInfoV2_fwVersionCustomer_get, _o3py.DeviceInfoV2_fwVersionCustomer_set)

    def __init__(self):
        _o3py.DeviceInfoV2_swiginit(self, _o3py.new_DeviceInfoV2())
    __swig_destroy__ = _o3py.delete_DeviceInfoV2

# Register DeviceInfoV2 in _o3py:
_o3py.DeviceInfoV2_swigregister(DeviceInfoV2)
class DeviceInfoV3(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    serialNumber = property(_o3py.DeviceInfoV3_serialNumber_get, _o3py.DeviceInfoV3_serialNumber_set)
    cpuId = property(_o3py.DeviceInfoV3_cpuId_get, _o3py.DeviceInfoV3_cpuId_set)
    cpuCode = property(_o3py.DeviceInfoV3_cpuCode_get, _o3py.DeviceInfoV3_cpuCode_set)
    cpuVersion = property(_o3py.DeviceInfoV3_cpuVersion_get, _o3py.DeviceInfoV3_cpuVersion_set)
    fwVersion = property(_o3py.DeviceInfoV3_fwVersion_get, _o3py.DeviceInfoV3_fwVersion_set)
    fwVersionBuild = property(_o3py.DeviceInfoV3_fwVersionBuild_get, _o3py.DeviceInfoV3_fwVersionBuild_set)
    fwVersionDate = property(_o3py.DeviceInfoV3_fwVersionDate_get, _o3py.DeviceInfoV3_fwVersionDate_set)
    fwVersionHash = property(_o3py.DeviceInfoV3_fwVersionHash_get, _o3py.DeviceInfoV3_fwVersionHash_set)
    fwVersionCustomer = property(_o3py.DeviceInfoV3_fwVersionCustomer_get, _o3py.DeviceInfoV3_fwVersionCustomer_set)
    hasUltrasonicSensor = property(_o3py.DeviceInfoV3_hasUltrasonicSensor_get, _o3py.DeviceInfoV3_hasUltrasonicSensor_set)
    tofSensorSerial = property(_o3py.DeviceInfoV3_tofSensorSerial_get, _o3py.DeviceInfoV3_tofSensorSerial_set)

    def __init__(self):
        _o3py.DeviceInfoV3_swiginit(self, _o3py.new_DeviceInfoV3())
    __swig_destroy__ = _o3py.delete_DeviceInfoV3

# Register DeviceInfoV3 in _o3py:
_o3py.DeviceInfoV3_swigregister(DeviceInfoV3)
class LensInfoV1(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    intrinsicsTof = property(_o3py.LensInfoV1_intrinsicsTof_get, _o3py.LensInfoV1_intrinsicsTof_set)
    lensModelToF = property(_o3py.LensInfoV1_lensModelToF_get, _o3py.LensInfoV1_lensModelToF_set)
    intrinsicsRgb = property(_o3py.LensInfoV1_intrinsicsRgb_get, _o3py.LensInfoV1_intrinsicsRgb_set)
    lensModelRgb = property(_o3py.LensInfoV1_lensModelRgb_get, _o3py.LensInfoV1_lensModelRgb_set)
    extrinsicsRgbToTof = property(_o3py.LensInfoV1_extrinsicsRgbToTof_get, _o3py.LensInfoV1_extrinsicsRgbToTof_set)

    def __init__(self):
        _o3py.LensInfoV1_swiginit(self, _o3py.new_LensInfoV1())
    __swig_destroy__ = _o3py.delete_LensInfoV1

# Register LensInfoV1 in _o3py:
_o3py.LensInfoV1_swigregister(LensInfoV1)
O3P_CAMERA_INFO_SERIAL_NUMBER = _o3py.O3P_CAMERA_INFO_SERIAL_NUMBER
O3P_CAMERA_INFO_CPU_ID = _o3py.O3P_CAMERA_INFO_CPU_ID
O3P_CAMERA_INFO_CPU_CODE = _o3py.O3P_CAMERA_INFO_CPU_CODE
O3P_CAMERA_INFO_CPU_VERSION = _o3py.O3P_CAMERA_INFO_CPU_VERSION
O3P_CAMERA_INFO_FW_VERSION = _o3py.O3P_CAMERA_INFO_FW_VERSION
O3P_CAMERA_INFO_FW_VERSION_BUILD = _o3py.O3P_CAMERA_INFO_FW_VERSION_BUILD
O3P_CAMERA_INFO_FW_VERSION_DATE = _o3py.O3P_CAMERA_INFO_FW_VERSION_DATE
O3P_CAMERA_INFO_FW_VERSION_HASH = _o3py.O3P_CAMERA_INFO_FW_VERSION_HASH
O3P_CAMERA_INFO_FW_VERSION_CUSTOMER = _o3py.O3P_CAMERA_INFO_FW_VERSION_CUSTOMER
O3P_CAMERA_INFO_HAS_ULTRASONIC_SENSOR = _o3py.O3P_CAMERA_INFO_HAS_ULTRASONIC_SENSOR
O3P_CAMERA_INFO_TOF_SENSOR_SERIAL = _o3py.O3P_CAMERA_INFO_TOF_SENSOR_SERIAL
O3P_CAMERA_INFO_COUNT = _o3py.O3P_CAMERA_INFO_COUNT

def cameraInfoToString(info):
    return _o3py.cameraInfoToString(info)

def getFileSize(filename):
    return _o3py.getFileSize(filename)
class Context(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def getAvailableCameras():
        return _o3py.Context_getAvailableCameras()

    @staticmethod
    def getConnectedDevices():
        return _o3py.Context_getConnectedDevices()

    @staticmethod
    def getInstance():
        return _o3py.Context_getInstance()

# Register Context in _o3py:
_o3py.Context_swigregister(Context)
class InfoInterface(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _o3py.delete_InfoInterface

    def supportsInfo(self, info):
        return _o3py.InfoInterface_supportsInfo(self, info)

    def getInfo(self, info):
        return _o3py.InfoInterface_getInfo(self, info)

# Register InfoInterface in _o3py:
_o3py.InfoInterface_swigregister(InfoInterface)
class InfoContainer(InfoInterface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _o3py.InfoContainer_swiginit(self, _o3py.new_InfoContainer())
    __swig_destroy__ = _o3py.delete_InfoContainer

    def addInfo(self, info, value):
        return _o3py.InfoContainer_addInfo(self, info, value)

    def updateInfo(self, info, value):
        return _o3py.InfoContainer_updateInfo(self, info, value)

    def supportsInfo(self, info):
        return _o3py.InfoContainer_supportsInfo(self, info)

    def getInfo(self, info):
        return _o3py.InfoContainer_getInfo(self, info)

# Register InfoContainer in _o3py:
_o3py.InfoContainer_swigregister(InfoContainer)
class OptionDescription(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _o3py.OptionDescription_swiginit(self, _o3py.new_OptionDescription(*args))
    __swig_destroy__ = _o3py.delete_OptionDescription

    def __eq__(self, other):
        return _o3py.OptionDescription___eq__(self, other)

    def __ne__(self, other):
        return _o3py.OptionDescription___ne__(self, other)

    def getName(self):
        return _o3py.OptionDescription_getName(self)

    def getDescription(self):
        return _o3py.OptionDescription_getDescription(self)

    def serialize(self):
        return _o3py.OptionDescription_serialize(self)

    @staticmethod
    def deserialize(data, size, bytesRead):
        return _o3py.OptionDescription_deserialize(data, size, bytesRead)

# Register OptionDescription in _o3py:
_o3py.OptionDescription_swigregister(OptionDescription)
O3P_OPTION_VALUE_TYPE_NONE = _o3py.O3P_OPTION_VALUE_TYPE_NONE
O3P_OPTION_VALUE_TYPE_INT = _o3py.O3P_OPTION_VALUE_TYPE_INT
O3P_OPTION_VALUE_TYPE_FLOAT = _o3py.O3P_OPTION_VALUE_TYPE_FLOAT
O3P_OPTION_VALUE_TYPE_STRING = _o3py.O3P_OPTION_VALUE_TYPE_STRING
O3P_OPTION_VALUE_TYPE_BOOL = _o3py.O3P_OPTION_VALUE_TYPE_BOOL
O3P_OPTION_VALUE_TYPE_MAX = _o3py.O3P_OPTION_VALUE_TYPE_MAX

def optionValueTypeToString(type):
    return _o3py.optionValueTypeToString(type)
class OptionValue(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __eq__(self, other):
        return _o3py.OptionValue___eq__(self, other)

    def __ne__(self, other):
        return _o3py.OptionValue___ne__(self, other)

    def __init__(self, *args):
        _o3py.OptionValue_swiginit(self, _o3py.new_OptionValue(*args))

    def getType(self):
        return _o3py.OptionValue_getType(self)

    def toJsonValue(self):
        return _o3py.OptionValue_toJsonValue(self)

    def asInt(self):
        return _o3py.OptionValue_asInt(self)

    def asFloat(self):
        return _o3py.OptionValue_asFloat(self)

    def asBool(self):
        return _o3py.OptionValue_asBool(self)

    def asString(self):
        return _o3py.OptionValue_asString(self)

    def __str__(self):
        return _o3py.OptionValue___str__(self)
    __swig_destroy__ = _o3py.delete_OptionValue

# Register OptionValue in _o3py:
_o3py.OptionValue_swigregister(OptionValue)
class OptionValueRange(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def __eq__(self, other):
        return _o3py.OptionValueRange___eq__(self, other)

    def __ne__(self, other):
        return _o3py.OptionValueRange___ne__(self, other)

    def isValid(self, value):
        return _o3py.OptionValueRange_isValid(self, value)

    def getType(self):
        return _o3py.OptionValueRange_getType(self)

    def __str__(self):
        return _o3py.OptionValueRange___str__(self)
    __swig_destroy__ = _o3py.delete_OptionValueRange

# Register OptionValueRange in _o3py:
_o3py.OptionValueRange_swigregister(OptionValueRange)
class IntOptionRange(OptionValueRange):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _o3py.IntOptionRange_swiginit(self, _o3py.new_IntOptionRange(*args))

    def getMin(self):
        return _o3py.IntOptionRange_getMin(self)

    def getMax(self):
        return _o3py.IntOptionRange_getMax(self)

    def getDefaultValue(self):
        return _o3py.IntOptionRange_getDefaultValue(self)

    def getStep(self):
        return _o3py.IntOptionRange_getStep(self)

    def isValid(self, value):
        return _o3py.IntOptionRange_isValid(self, value)

    @staticmethod
    def fromRange(range):
        return _o3py.IntOptionRange_fromRange(range)
    __swig_destroy__ = _o3py.delete_IntOptionRange

# Register IntOptionRange in _o3py:
_o3py.IntOptionRange_swigregister(IntOptionRange)
class FloatOptionRange(OptionValueRange):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _o3py.FloatOptionRange_swiginit(self, _o3py.new_FloatOptionRange(*args))

    def getMin(self):
        return _o3py.FloatOptionRange_getMin(self)

    def getMax(self):
        return _o3py.FloatOptionRange_getMax(self)

    def getDefaultValue(self):
        return _o3py.FloatOptionRange_getDefaultValue(self)

    def getStep(self):
        return _o3py.FloatOptionRange_getStep(self)

    def isValid(self, value):
        return _o3py.FloatOptionRange_isValid(self, value)

    @staticmethod
    def fromRange(range):
        return _o3py.FloatOptionRange_fromRange(range)
    __swig_destroy__ = _o3py.delete_FloatOptionRange

# Register FloatOptionRange in _o3py:
_o3py.FloatOptionRange_swigregister(FloatOptionRange)
class StringOptionRange(OptionValueRange):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _o3py.StringOptionRange_swiginit(self, _o3py.new_StringOptionRange(*args))

    def getDefaultValue(self):
        return _o3py.StringOptionRange_getDefaultValue(self)

    def getAllowedValues(self):
        return _o3py.StringOptionRange_getAllowedValues(self)

    def isValid(self, value):
        return _o3py.StringOptionRange_isValid(self, value)

    @staticmethod
    def fromRange(range):
        return _o3py.StringOptionRange_fromRange(range)
    __swig_destroy__ = _o3py.delete_StringOptionRange

# Register StringOptionRange in _o3py:
_o3py.StringOptionRange_swigregister(StringOptionRange)
O3P_OPTION_NONE = _o3py.O3P_OPTION_NONE
O3P_OPTION_TOF_ENABLE_AUTO_EXPOSURE = _o3py.O3P_OPTION_TOF_ENABLE_AUTO_EXPOSURE
O3P_OPTION_TOF_MANUAL_EXPOSURE_TIME_1 = _o3py.O3P_OPTION_TOF_MANUAL_EXPOSURE_TIME_1
O3P_OPTION_TOF_MANUAL_EXPOSURE_TIME_2 = _o3py.O3P_OPTION_TOF_MANUAL_EXPOSURE_TIME_2
O3P_OPTION_COLOR_SCHEME = _o3py.O3P_OPTION_COLOR_SCHEME
O3P_OPTION_COLOR_HISTOGRAM_EQUALIZATION = _o3py.O3P_OPTION_COLOR_HISTOGRAM_EQUALIZATION
O3P_OPTION_COLOR_MIN_DEPTH = _o3py.O3P_OPTION_COLOR_MIN_DEPTH
O3P_OPTION_COLOR_MAX_DEPTH = _o3py.O3P_OPTION_COLOR_MAX_DEPTH
O3P_OPTION_RGB_ENABLE_AUTO_EXPOSURE = _o3py.O3P_OPTION_RGB_ENABLE_AUTO_EXPOSURE
O3P_OPTION_RGB_MANUAL_EXPOSURE_TIME_1 = _o3py.O3P_OPTION_RGB_MANUAL_EXPOSURE_TIME_1
O3P_OPTION_RGB_MANUAL_EXPOSURE_TIME_2 = _o3py.O3P_OPTION_RGB_MANUAL_EXPOSURE_TIME_2
O3P_OPTION_RGB_ENABLE_AUTO_ANALOG_GAIN = _o3py.O3P_OPTION_RGB_ENABLE_AUTO_ANALOG_GAIN
O3P_OPTION_RGB_MANUAL_ANALOG_GAIN = _o3py.O3P_OPTION_RGB_MANUAL_ANALOG_GAIN
O3P_OPTION_RGB_ENABLE_AUTO_WHITE_BALANCE = _o3py.O3P_OPTION_RGB_ENABLE_AUTO_WHITE_BALANCE
O3P_OPTION_RGB_MANUAL_WHITE_BALANCE = _o3py.O3P_OPTION_RGB_MANUAL_WHITE_BALANCE
O3P_OPTION_MAX = _o3py.O3P_OPTION_MAX

def optionTypeToString(type):
    return _o3py.optionTypeToString(type)

def stringToOptionType(str):
    return _o3py.stringToOptionType(str)
class OptionInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _o3py.OptionInfo_swiginit(self, _o3py.new_OptionInfo(*args))
    __swig_destroy__ = _o3py.delete_OptionInfo

    def __eq__(self, other):
        return _o3py.OptionInfo___eq__(self, other)

    def __ne__(self, other):
        return _o3py.OptionInfo___ne__(self, other)

    def getType(self):
        return _o3py.OptionInfo_getType(self)

    def getValueType(self):
        return _o3py.OptionInfo_getValueType(self)

    def getRange(self):
        return _o3py.OptionInfo_getRange(self)

    def getDescription(self):
        return _o3py.OptionInfo_getDescription(self)

    def getName(self):
        return _o3py.OptionInfo_getName(self)

    def serialize(self):
        return _o3py.OptionInfo_serialize(self)

    @staticmethod
    def deserialize(data, size, bytesRead):
        return _o3py.OptionInfo_deserialize(data, size, bytesRead)

    def isEnabled(self):
        return _o3py.OptionInfo_isEnabled(self)

    def isReadOnly(self):
        return _o3py.OptionInfo_isReadOnly(self)

# Register OptionInfo in _o3py:
_o3py.OptionInfo_swigregister(OptionInfo)
class Option(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def getValue(self):
        return _o3py.Option_getValue(self)

    def setValue(self, newValue):
        return _o3py.Option_setValue(self, newValue)

    def getName(self):
        return _o3py.Option_getName(self)

    def getDescription(self):
        return _o3py.Option_getDescription(self)

    def getType(self):
        return _o3py.Option_getType(self)

    def getValueType(self):
        return _o3py.Option_getValueType(self)

    def getRange(self):
        return _o3py.Option_getRange(self)

    def getInfo(self):
        return _o3py.Option_getInfo(self)

    def isEnabled(self):
        return _o3py.Option_isEnabled(self)

    def isReadOnly(self):
        return _o3py.Option_isReadOnly(self)

    def __init__(self):
        _o3py.Option_swiginit(self, _o3py.new_Option())
    __swig_destroy__ = _o3py.delete_Option

# Register Option in _o3py:
_o3py.Option_swigregister(Option)
class OptionsInterface(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _o3py.delete_OptionsInterface

    def getOption(self, optionType):
        return _o3py.OptionsInterface_getOption(self, optionType)

    def supportsOption(self, optionType):
        return _o3py.OptionsInterface_supportsOption(self, optionType)

# Register OptionsInterface in _o3py:
_o3py.OptionsInterface_swigregister(OptionsInterface)
class Device(InfoInterface, OptionsInterface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _o3py.delete_Device

    def init(self):
        return _o3py.Device_init(self)

    def start(self):
        return _o3py.Device_start(self)

    def stop(self):
        return _o3py.Device_stop(self)

    def closeDevice(self):
        return _o3py.Device_closeDevice(self)

    def waitForFrames(self, frameSet):
        return _o3py.Device_waitForFrames(self, frameSet)

    def getStreams(self):
        return _o3py.Device_getStreams(self)

    def sendPluginMessage(self, message):
        return _o3py.Device_sendPluginMessage(self, message)

    def setConfigValue(self, config, value):
        return _o3py.Device_setConfigValue(self, config, value)

    def getConfigValue(self, config):
        return _o3py.Device_getConfigValue(self, config)

    def saveConfig(self):
        return _o3py.Device_saveConfig(self)

    def writeEeprom(self, value):
        return _o3py.Device_writeEeprom(self, value)

    def readEeprom(self):
        return _o3py.Device_readEeprom(self)

    def getLicenseInfo(self):
        return _o3py.Device_getLicenseInfo(self)

    def getId(self):
        return _o3py.Device_getId(self)

    def setDisconnectCallback(self, cb):
        return _o3py.Device_setDisconnectCallback(self, cb)

    def getNumberOfFrames(self):
        return _o3py.Device_getNumberOfFrames(self)

    def getFwLogger(self):
        return _o3py.Device_getFwLogger(self)

    def getAndResetDroppedFrames(self):
        return _o3py.Device_getAndResetDroppedFrames(self)

    def supportsInfo(self, info):
        return _o3py.Device_supportsInfo(self, info)

    def getInfo(self, info):
        return _o3py.Device_getInfo(self, info)

    def supportsOption(self, optionType):
        return _o3py.Device_supportsOption(self, optionType)

    def getOption(self, optionType):
        return _o3py.Device_getOption(self, optionType)

# Register Device in _o3py:
_o3py.Device_swigregister(Device)
class Frame(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _o3py.delete_Frame

    def __init__(self, *args):
        _o3py.Frame_swiginit(self, _o3py.new_Frame(*args))

    def getTimestamp(self):
        return _o3py.Frame_getTimestamp(self)

    def supportsMetadata(self, type):
        return _o3py.Frame_supportsMetadata(self, type)
    m_timestamp = property(_o3py.Frame_m_timestamp_get, _o3py.Frame_m_timestamp_set)
    m_metadataBuffer = property(_o3py.Frame_m_metadataBuffer_get, _o3py.Frame_m_metadataBuffer_set)
    m_metadataLayout = property(_o3py.Frame_m_metadataLayout_get, _o3py.Frame_m_metadataLayout_set)

    def getMetadataUint32(self, type):
        return _o3py.Frame_getMetadataUint32(self, type)

    def getMetadataUint64(self, type):
        return _o3py.Frame_getMetadataUint64(self, type)

    def getMetadataFloat(self, type):
        return _o3py.Frame_getMetadataFloat(self, type)

    def getMetadataBool(self, type):
        return _o3py.Frame_getMetadataBool(self, type)

# Register Frame in _o3py:
_o3py.Frame_swigregister(Frame)
class VideoFrame(Frame):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _o3py.VideoFrame_swiginit(self, _o3py.new_VideoFrame(*args))

    def getWidth(self):
        return _o3py.VideoFrame_getWidth(self)

    def getHeight(self):
        return _o3py.VideoFrame_getHeight(self)
    m_width = property(_o3py.VideoFrame_m_width_get, _o3py.VideoFrame_m_width_set)
    m_height = property(_o3py.VideoFrame_m_height_get, _o3py.VideoFrame_m_height_set)
    m_bitsPerPixel = property(_o3py.VideoFrame_m_bitsPerPixel_get, _o3py.VideoFrame_m_bitsPerPixel_set)
    m_data = property(_o3py.VideoFrame_m_data_get, _o3py.VideoFrame_m_data_set)
    m_isCopy = property(_o3py.VideoFrame_m_isCopy_get, _o3py.VideoFrame_m_isCopy_set)
    m_dataCopy = property(_o3py.VideoFrame_m_dataCopy_get, _o3py.VideoFrame_m_dataCopy_set)

    def getData(self):
        return _o3py.VideoFrame_getData(self)
    __swig_destroy__ = _o3py.delete_VideoFrame

# Register VideoFrame in _o3py:
_o3py.VideoFrame_swigregister(VideoFrame)
class DepthFrame(Frame):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _o3py.DepthFrame_swiginit(self, _o3py.new_DepthFrame(*args))

    def getWidth(self):
        return _o3py.DepthFrame_getWidth(self)

    def getHeight(self):
        return _o3py.DepthFrame_getHeight(self)

    def getDistance(self, x, y):
        return _o3py.DepthFrame_getDistance(self, x, y)
    m_width = property(_o3py.DepthFrame_m_width_get, _o3py.DepthFrame_m_width_set)
    m_height = property(_o3py.DepthFrame_m_height_get, _o3py.DepthFrame_m_height_set)
    m_data = property(_o3py.DepthFrame_m_data_get, _o3py.DepthFrame_m_data_set)
    m_isCopy = property(_o3py.DepthFrame_m_isCopy_get, _o3py.DepthFrame_m_isCopy_set)
    m_dataCopy = property(_o3py.DepthFrame_m_dataCopy_get, _o3py.DepthFrame_m_dataCopy_set)

    def getData(self):
        return _o3py.DepthFrame_getData(self)
    __swig_destroy__ = _o3py.delete_DepthFrame

# Register DepthFrame in _o3py:
_o3py.DepthFrame_swigregister(DepthFrame)
class PointcloudFrame(Frame):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _o3py.PointcloudFrame_swiginit(self, _o3py.new_PointcloudFrame(*args))

    def getWidth(self):
        return _o3py.PointcloudFrame_getWidth(self)

    def getHeight(self):
        return _o3py.PointcloudFrame_getHeight(self)

    def getX(self, x, y):
        return _o3py.PointcloudFrame_getX(self, x, y)

    def getY(self, x, y):
        return _o3py.PointcloudFrame_getY(self, x, y)

    def getZ(self, x, y):
        return _o3py.PointcloudFrame_getZ(self, x, y)

    def getConfidence(self, x, y):
        return _o3py.PointcloudFrame_getConfidence(self, x, y)
    m_width = property(_o3py.PointcloudFrame_m_width_get, _o3py.PointcloudFrame_m_width_set)
    m_height = property(_o3py.PointcloudFrame_m_height_get, _o3py.PointcloudFrame_m_height_set)
    m_data = property(_o3py.PointcloudFrame_m_data_get, _o3py.PointcloudFrame_m_data_set)
    m_isCopy = property(_o3py.PointcloudFrame_m_isCopy_get, _o3py.PointcloudFrame_m_isCopy_set)
    m_dataCopy = property(_o3py.PointcloudFrame_m_dataCopy_get, _o3py.PointcloudFrame_m_dataCopy_set)

    def getData(self):
        return _o3py.PointcloudFrame_getData(self)
    __swig_destroy__ = _o3py.delete_PointcloudFrame

# Register PointcloudFrame in _o3py:
_o3py.PointcloudFrame_swigregister(PointcloudFrame)
class ImuFrame(Frame):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _o3py.ImuFrame_swiginit(self, _o3py.new_ImuFrame())
    angularVelocity = property(_o3py.ImuFrame_angularVelocity_get, _o3py.ImuFrame_angularVelocity_set)
    angularTimestamp = property(_o3py.ImuFrame_angularTimestamp_get, _o3py.ImuFrame_angularTimestamp_set)
    acceleration = property(_o3py.ImuFrame_acceleration_get, _o3py.ImuFrame_acceleration_set)
    accelerationTimestamp = property(_o3py.ImuFrame_accelerationTimestamp_get, _o3py.ImuFrame_accelerationTimestamp_set)

    def getAcceleration(self):
        return _o3py.ImuFrame_getAcceleration(self)

    def getAngularVelocity(self):
        return _o3py.ImuFrame_getAngularVelocity(self)
    __swig_destroy__ = _o3py.delete_ImuFrame

# Register ImuFrame in _o3py:
_o3py.ImuFrame_swigregister(ImuFrame)
class UltrasonicFrame(Frame):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _o3py.UltrasonicFrame_swiginit(self, _o3py.new_UltrasonicFrame())

    def getDistance(self):
        return _o3py.UltrasonicFrame_getDistance(self)

    def getTimestamp(self):
        return _o3py.UltrasonicFrame_getTimestamp(self)

    def getSignalWidth(self):
        return _o3py.UltrasonicFrame_getSignalWidth(self)

    def getAmplitude(self):
        return _o3py.UltrasonicFrame_getAmplitude(self)

    def getTemperature(self):
        return _o3py.UltrasonicFrame_getTemperature(self)
    m_data = property(_o3py.UltrasonicFrame_m_data_get, _o3py.UltrasonicFrame_m_data_set)
    __swig_destroy__ = _o3py.delete_UltrasonicFrame

# Register UltrasonicFrame in _o3py:
_o3py.UltrasonicFrame_swigregister(UltrasonicFrame)
class PluginFrame(Frame):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _o3py.PluginFrame_swiginit(self, _o3py.new_PluginFrame())

    def getData(self):
        return _o3py.PluginFrame_getData(self)

    def getSize(self):
        return _o3py.PluginFrame_getSize(self)
    m_size = property(_o3py.PluginFrame_m_size_get, _o3py.PluginFrame_m_size_set)
    m_data = property(_o3py.PluginFrame_m_data_get, _o3py.PluginFrame_m_data_set)

    def getPluginData(self):
        return _o3py.PluginFrame_getPluginData(self)
    __swig_destroy__ = _o3py.delete_PluginFrame

# Register PluginFrame in _o3py:
_o3py.PluginFrame_swigregister(PluginFrame)
class FrameSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _o3py.FrameSet_swiginit(self, _o3py.new_FrameSet(*args))

    def getColorFrame(self):
        return _o3py.FrameSet_getColorFrame(self)

    def getInfraredFrame(self):
        return _o3py.FrameSet_getInfraredFrame(self)

    def getDepthFrame(self):
        return _o3py.FrameSet_getDepthFrame(self)

    def getImuFrame(self):
        return _o3py.FrameSet_getImuFrame(self)

    def getUltrasonicFrame(self):
        return _o3py.FrameSet_getUltrasonicFrame(self)

    def getPointCloudFrame(self):
        return _o3py.FrameSet_getPointCloudFrame(self)

    def getPluginFrame(self):
        return _o3py.FrameSet_getPluginFrame(self)
    m_colorFrame = property(_o3py.FrameSet_m_colorFrame_get, _o3py.FrameSet_m_colorFrame_set)
    m_infraredFrame = property(_o3py.FrameSet_m_infraredFrame_get, _o3py.FrameSet_m_infraredFrame_set)
    m_depthFrame = property(_o3py.FrameSet_m_depthFrame_get, _o3py.FrameSet_m_depthFrame_set)
    m_imuFrame = property(_o3py.FrameSet_m_imuFrame_get, _o3py.FrameSet_m_imuFrame_set)
    m_pointcloudFrame = property(_o3py.FrameSet_m_pointcloudFrame_get, _o3py.FrameSet_m_pointcloudFrame_set)
    m_ultrasonicFrame = property(_o3py.FrameSet_m_ultrasonicFrame_get, _o3py.FrameSet_m_ultrasonicFrame_set)
    m_pluginFrame = property(_o3py.FrameSet_m_pluginFrame_get, _o3py.FrameSet_m_pluginFrame_set)
    __swig_destroy__ = _o3py.delete_FrameSet

# Register FrameSet in _o3py:
_o3py.FrameSet_swigregister(FrameSet)
class Stream(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, streamType):
        _o3py.Stream_swiginit(self, _o3py.new_Stream(streamType))
    __swig_destroy__ = _o3py.delete_Stream

    def streamType(self):
        return _o3py.Stream_streamType(self)

    def setId(self, id):
        return _o3py.Stream_setId(self, id)

    def id(self):
        return _o3py.Stream_id(self)

# Register Stream in _o3py:
_o3py.Stream_swigregister(Stream)
class VideoStream(Stream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, width, height, intrinsics, extrinsics, streamType):
        _o3py.VideoStream_swiginit(self, _o3py.new_VideoStream(width, height, intrinsics, extrinsics, streamType))

    def width(self):
        return _o3py.VideoStream_width(self)

    def height(self):
        return _o3py.VideoStream_height(self)

    def getIntrinsics(self):
        return _o3py.VideoStream_getIntrinsics(self)

    def getExtrinsicsTo(self, to):
        return _o3py.VideoStream_getExtrinsicsTo(self, to)

    def getExtrinsics(self):
        return _o3py.VideoStream_getExtrinsics(self)

    @staticmethod
    def fromStream(stream):
        return _o3py.VideoStream_fromStream(stream)
    __swig_destroy__ = _o3py.delete_VideoStream

# Register VideoStream in _o3py:
_o3py.VideoStream_swigregister(VideoStream)
class PipelineConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _o3py.PipelineConfig_swiginit(self, _o3py.new_PipelineConfig(*args))

    def setPlaybackFile(self, playbackFile):
        return _o3py.PipelineConfig_setPlaybackFile(self, playbackFile)

    def getPlaybackFile(self):
        return _o3py.PipelineConfig_getPlaybackFile(self)

    def setLoopPlayback(self, loopPlayback):
        return _o3py.PipelineConfig_setLoopPlayback(self, loopPlayback)

    def getLoopPlayback(self):
        return _o3py.PipelineConfig_getLoopPlayback(self)

    def setUseTimestampsPlayback(self, useTimestampsPlayback):
        return _o3py.PipelineConfig_setUseTimestampsPlayback(self, useTimestampsPlayback)

    def getUseTimestampsPlayback(self):
        return _o3py.PipelineConfig_getUseTimestampsPlayback(self)

    def enableDevice(self, id):
        return _o3py.PipelineConfig_enableDevice(self, id)

    def getDeviceId(self):
        return _o3py.PipelineConfig_getDeviceId(self)

    def setDisconnectCallback(self, callback):
        return _o3py.PipelineConfig_setDisconnectCallback(self, callback)

    def getDisconnectCallback(self):
        return _o3py.PipelineConfig_getDisconnectCallback(self)

    def __eq__(self, other):
        return _o3py.PipelineConfig___eq__(self, other)

    def __ne__(self, other):
        return _o3py.PipelineConfig___ne__(self, other)
    __swig_destroy__ = _o3py.delete_PipelineConfig

# Register PipelineConfig in _o3py:
_o3py.PipelineConfig_swigregister(PipelineConfig)
class PipelineProfile(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def getStreams(self):
        return _o3py.PipelineProfile_getStreams(self)

    def getSerialNumber(self):
        return _o3py.PipelineProfile_getSerialNumber(self)

    def getDevice(self):
        return _o3py.PipelineProfile_getDevice(self)

    def __init__(self, *args):
        _o3py.PipelineProfile_swiginit(self, _o3py.new_PipelineProfile(*args))

    def getDeviceInfo(self, infoType):
        return _o3py.PipelineProfile_getDeviceInfo(self, infoType)
    __swig_destroy__ = _o3py.delete_PipelineProfile

# Register PipelineProfile in _o3py:
_o3py.PipelineProfile_swigregister(PipelineProfile)
class Pipeline(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _o3py.Pipeline_swiginit(self, _o3py.new_Pipeline())
    __swig_destroy__ = _o3py.delete_Pipeline

    def init(self, *args):
        return _o3py.Pipeline_init(self, *args)

    def start(self):
        return _o3py.Pipeline_start(self)

    def stop(self):
        return _o3py.Pipeline_stop(self)

    def waitForFrames(self):
        return _o3py.Pipeline_waitForFrames(self)

    def sendPluginMessage(self, message):
        return _o3py.Pipeline_sendPluginMessage(self, message)

    def getConfigValue(self, config):
        return _o3py.Pipeline_getConfigValue(self, config)

    def setConfigValue(self, config, value):
        return _o3py.Pipeline_setConfigValue(self, config, value)

    def writeEeprom(self, value):
        return _o3py.Pipeline_writeEeprom(self, value)

    def readEeprom(self):
        return _o3py.Pipeline_readEeprom(self)

    def getLicenseInfo(self):
        return _o3py.Pipeline_getLicenseInfo(self)

    def getAvailableUseCases(self):
        return _o3py.Pipeline_getAvailableUseCases(self)

    def getUseCase(self):
        return _o3py.Pipeline_getUseCase(self)

    def setUseCase(self, useCase):
        return _o3py.Pipeline_setUseCase(self, useCase)

    def loadPreset(self, preset):
        return _o3py.Pipeline_loadPreset(self, preset)

    def getAvailablePresets(self):
        return _o3py.Pipeline_getAvailablePresets(self)

    def setCameraParameters(self, fps, hdr, range, distanceOffset=0):
        return _o3py.Pipeline_setCameraParameters(self, fps, hdr, range, distanceOffset)

    def checkCameraParameters(self, fps, hdr, range, distanceOffset=0):
        return _o3py.Pipeline_checkCameraParameters(self, fps, hdr, range, distanceOffset)

    def saveCameraParameters(self):
        return _o3py.Pipeline_saveCameraParameters(self)

    def setFPS(self, fps):
        return _o3py.Pipeline_setFPS(self, fps)

    def getFPS(self):
        return _o3py.Pipeline_getFPS(self)

    def getAvailableFPS(self):
        return _o3py.Pipeline_getAvailableFPS(self)

    def getAllAvailableFPS(self):
        return _o3py.Pipeline_getAllAvailableFPS(self)

    def setHDR(self, on):
        return _o3py.Pipeline_setHDR(self, on)

    def getHDR(self):
        return _o3py.Pipeline_getHDR(self)

    def getAvailableHDR(self):
        return _o3py.Pipeline_getAvailableHDR(self)

    def getAllAvailableHDR(self):
        return _o3py.Pipeline_getAllAvailableHDR(self)

    def setMeasurementRange(self, range):
        return _o3py.Pipeline_setMeasurementRange(self, range)

    def getMeasurementRange(self):
        return _o3py.Pipeline_getMeasurementRange(self)

    def getAvailableMeasurementRanges(self):
        return _o3py.Pipeline_getAvailableMeasurementRanges(self)

    def getAllAvailableMeasurementRanges(self):
        return _o3py.Pipeline_getAllAvailableMeasurementRanges(self)

    def setDistanceOffset(self, offset):
        return _o3py.Pipeline_setDistanceOffset(self, offset)

    def getDistanceOffset(self):
        return _o3py.Pipeline_getDistanceOffset(self)

    def getAvailableDistanceOffsets(self):
        return _o3py.Pipeline_getAvailableDistanceOffsets(self)

    def getAllAvailableDistanceOffsets(self):
        return _o3py.Pipeline_getAllAvailableDistanceOffsets(self)

    def startRecording(self, filename):
        return _o3py.Pipeline_startRecording(self, filename)

    def stopRecording(self):
        return _o3py.Pipeline_stopRecording(self)

    def getActiveProfile(self):
        return _o3py.Pipeline_getActiveProfile(self)

    def getDevice(self):
        return _o3py.Pipeline_getDevice(self)

    def getAndResetDroppedFrames(self):
        return _o3py.Pipeline_getAndResetDroppedFrames(self)

    def setRecordingFps(self, recFps):
        return _o3py.Pipeline_setRecordingFps(self, recFps)

    def getNumberOfFramesInRecording(self):
        return _o3py.Pipeline_getNumberOfFramesInRecording(self)

    def enableAI(self, enable):
        return _o3py.Pipeline_enableAI(self, enable)

# Register Pipeline in _o3py:
_o3py.Pipeline_swigregister(Pipeline)

