/****************************************************************************\
* Copyright (C) 2026 pmdtechnologies gmbh
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
* ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
* THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
* BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
* GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
* OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
\****************************************************************************/

#ifndef LENSMODELTYPE_HPP
#define LENSMODELTYPE_HPP

/**
 * @brief Lens Model entry
 */
enum LensModelType {
    RESERVED = 0,
    /**< OpenCV Pin hole camera model, real or virtual grid is not specified */
    PIN_HOLE = 1,
    /**< as PIN_HOLE, lens parameters for the real pixels */
    PIN_HOLE_REAL = 2,
    /**< as PIN_HOLE, lens parameters for the virtual pixel */
    PIN_HOLE_VIRTUAL = 3,
    /**< fish eye */
    FISH_EYE = 4
};

typedef enum LensModelType LensModel;

#endif // LENSMODELTYPE_HPP
