#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""Host-side automatic pipeline: home/perception pose -> vision -> execute."""

import argparse
import importlib.util
import os
import re
import shlex
import subprocess
import sys
import time
from pathlib import Path

import yaml


REPO = Path("/home/i6user/Desktop/robot_lego")
DOCKER_CONTAINER = "vision_node_final"
MIN_ROBOT_PIPELINE_WAIT_S = 35.0
VISION_BRIDGE_HOST = REPO / "src/my_robot_vision/my_robot_vision/vision_node_test1_5_bridge.py"
PLAN_HOST = REPO / "src/panda_pick/src/plan_perception_test.yaml"
PLAN_FROM_PRODUCT_HOST = REPO / "src/panda_pick/src/plan_from_product.yaml"
PLANNER_SCRIPT = REPO / "src/panda_pick/src/myplanner.py"
PLAN_DOCKER = "/vision_code/plan_perception_test.yaml"
TARGET_DOCKER = "/shared_data/current_target.txt"
VISION_OUTPUT_DOCKER = "/shared_data/vision_output.yaml"
VISION_PID_DOCKER = "/shared_data/vision_bridge.pid"
VISION_OUTPUT_HOST = REPO / "FoundationPose/root/FoundationPose/vision_output.yaml"
VISION_CACHE_DIR = REPO / "FoundationPose/root/FoundationPose/vision_cache"
BRIDGE_CONFIG = REPO / "src/my_robot_vision/config/vision_execution_bridge.yaml"
TASK_FILE = REPO / "src/panda_pick/config/pick_place_task.yaml"
TAUGHT_ENV = REPO / "src/panda_pick/config/ur5_taught_joints.env"


def run(cmd, *, check=True, cwd=REPO):
    print(f"\n[AUTO] $ {cmd}")
    result = subprocess.run(cmd, shell=True, cwd=str(cwd), text=True)
    if check and result.returncode != 0:
        raise RuntimeError(f"command failed with code {result.returncode}: {cmd}")
    return result.returncode


def capture(cmd, *, check=True, cwd=REPO):
    result = subprocess.run(
        cmd,
        shell=True,
        cwd=str(cwd),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    if check and result.returncode != 0:
        print(result.stdout)
        raise RuntimeError(f"command failed with code {result.returncode}: {cmd}")
    return result.stdout


def print_timing(metric, seconds, **fields):
    details = [f"{metric}={float(seconds):.3f}"]
    for key, value in fields.items():
        details.append(f"{key}={shlex.quote(str(value))}")
    print("[AUTO][TIMING] " + " ".join(details))


def load_yaml(path):
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        raise RuntimeError(f"{path} must contain a YAML mapping")
    return data


def write_yaml(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, sort_keys=False)


def ros_bash(command):
    return (
        "bash -lc "
        + shlex.quote(
            "cd /home/i6user/Desktop/robot_lego && "
            "source /opt/ros/humble/setup.bash && "
            "source install/setup.bash && "
            "source src/panda_pick/config/ur5_taught_joints.env && "
            + command
        )
    )


def docker_exec(docker_cmd, command, *, check=True):
    env_args = []
    display = os.environ.get("DISPLAY")
    if display:
        env_args.extend([
            "-e",
            f"DISPLAY={display}",
            "-e",
            "QT_X11_NO_MITSHM=1",
            "-e",
            "XAUTHORITY=",
        ])
    env_text = " ".join(shlex.quote(item) for item in env_args)
    if env_text:
        env_text += " "
    return run(f"{docker_cmd} exec {env_text}{DOCKER_CONTAINER} bash -lc {shlex.quote(command)}", check=check)


def write_plan(target, place_xyz, grasp_spin, blueprint_yaw):
    PLAN_HOST.parent.mkdir(parents=True, exist_ok=True)
    PLAN_HOST.write_text(
        f"""# Auto-generated by run_auto_pick_pipeline.py
tasksh:
  - id: 0
    name: {target}
    grasp_spin: {grasp_spin}
    blueprint_yaw: {blueprint_yaw}
    pick:
      pos: [0.0, 0.0, 0.0]
      orientation: [0.70710678, 0.70710678, 0.0, 0.0]
    place:
      pos: [{place_xyz[0]:.4f}, {place_xyz[1]:.4f}, {place_xyz[2]:.4f}]
      orientation: [0.70710678, 0.70710678, 0.0, 0.0]
""",
        encoding="utf-8",
    )
    print(f"[AUTO] wrote planner target: {PLAN_HOST}")


def task_target(task):
    for key in ("vision_label", "vision_name", "target", "name"):
        value = task.get(key)
        if value:
            return str(value).strip()
    raise RuntimeError(f"planner task has no target/name field: {task}")


def write_active_plan_task(task):
    write_yaml(PLAN_HOST, {"tasksh": [task]})
    print(f"[AUTO] wrote active planner task: {PLAN_HOST}")


def write_plan_tasks(tasks):
    tasks = list(tasks)
    write_yaml(PLAN_HOST, {"tasksh": tasks})
    print(f"[AUTO] wrote {len(tasks)} planner task(s): {PLAN_HOST}")


def load_plan_tasks(path):
    plan = load_yaml(path)
    tasks = plan.get("tasksh", plan.get("tasks", []))
    if not isinstance(tasks, list) or not tasks:
        raise RuntimeError(f"planner output has no tasksh/tasks list: {path}")
    return tasks


def generate_product_plan(product_yaml, output_yaml):
    if not PLANNER_SCRIPT.exists():
        raise RuntimeError(f"missing planner script: {PLANNER_SCRIPT}")
    start = time.perf_counter()
    spec = importlib.util.spec_from_file_location("panda_pick_myplanner", str(PLANNER_SCRIPT))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.process_blueprint(str(product_yaml), str(output_yaml))
    elapsed = time.perf_counter() - start
    print(f"[AUTO] generated product plan: {output_yaml}")
    print_timing("planner_time_s", elapsed, product_yaml=product_yaml.name)
    return elapsed


def safe_cache_name(text):
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(text).strip()).strip("_")
    cleaned = cleaned.strip("._-")
    return cleaned[:80] or "target"


def vision_cache_path(index, target):
    return VISION_CACHE_DIR / f"{index:02d}_{safe_cache_name(target)}.yaml"


def stop_vision_service(docker_cmd):
    # Keep this in a separate shell from the start command. If the same shell
    # also contains "python vision_node_test1_5_bridge.py", pkill -f can match
    # and terminate its own docker exec session with SIGTERM/code 143.
    stop_cmd = (
        f"if [ -s {shlex.quote(VISION_PID_DOCKER)} ]; then "
        f"pid=$(cat {shlex.quote(VISION_PID_DOCKER)}); "
        'kill "$pid" 2>/dev/null || true; '
        "fi; "
        "pkill -f '[v]ision_node_test1_5_bridge.py' || true; "
        f"rm -f {shlex.quote(VISION_PID_DOCKER)}"
    )
    docker_exec(docker_cmd, stop_cmd, check=False)


def ensure_vision_service(docker_cmd, target, *, frozen_observation=False):
    run(f"{docker_cmd} start {DOCKER_CONTAINER}", check=False)
    run(f"{docker_cmd} cp {shlex.quote(str(VISION_BRIDGE_HOST))} {DOCKER_CONTAINER}:/vision_code/vision_node_test1_5_bridge.py")
    run(f"{docker_cmd} cp {shlex.quote(str(PLAN_HOST))} {DOCKER_CONTAINER}:{PLAN_DOCKER}")
    stop_vision_service(docker_cmd)

    # Keep one bridge process alive inside Docker. It waits for TARGET_DOCKER.
    start_cmd = (
        f"rm -f {shlex.quote(TARGET_DOCKER)} {shlex.quote(VISION_OUTPUT_DOCKER)} "
        f"{shlex.quote(VISION_PID_DOCKER)}; "
        "cd /vision_code; "
        "nohup env "
        f"PLAN_YAML={shlex.quote(PLAN_DOCKER)} "
        f"TARGET_FILE={shlex.quote(TARGET_DOCKER)} "
        f"OUTPUT_FILE={shlex.quote(VISION_OUTPUT_DOCKER)} "
        f"VISION_FROZEN_OBSERVATION={'1' if frozen_observation else '0'} "
        "/opt/conda/envs/my/bin/python vision_node_test1_5_bridge.py "
        ">/shared_data/vision_bridge.log 2>&1 < /dev/null & "
        f"echo $! > {shlex.quote(VISION_PID_DOCKER)}; "
        "sleep 1; "
        f"pid=$(cat {shlex.quote(VISION_PID_DOCKER)}); "
        'kill -0 "$pid" 2>/dev/null || '
        "(tail -80 /shared_data/vision_bridge.log; exit 1)"
    )
    docker_exec(docker_cmd, start_cmd)
    mode = "frozen-observe async" if frozen_observation else "live"
    print(f"[AUTO] vision bridge starting for target: {target} ({mode})")


def move_to_observe_pose():
    print("[AUTO] moving robot to observe pose from UR5_OBSERVE_JOINTS")
    cmd = (
        "ros2 launch panda_pick run_ur5.launch.py "
        "motion_control_mode:=joint_ptp "
        "gripper_control_mode:=none "
        'urscript_pregrasp_joints:="$UR5_OBSERVE_JOINTS" '
        'urscript_home_joints:="$UR5_OBSERVE_JOINTS" '
        "joint_ptp_return_home:=false "
        "joint_ptp_dwell_seconds:=0.1 "
        "urscript_pipeline_wait_seconds:=8.0 "
        "urscript_movej_velocity:=0.90 "
        "urscript_movej_acceleration:=2.0"
    )
    run(ros_bash(cmd))


def trigger_vision(docker_cmd, target):
    trigger = (
        f"rm -f {shlex.quote(VISION_OUTPUT_DOCKER)}; "
        f"printf %s {shlex.quote(target)} > {shlex.quote(TARGET_DOCKER)}"
    )
    docker_exec(docker_cmd, trigger)
    print(f"[AUTO] triggered vision target: {target}")


def wait_for_vision_output(docker_cmd, timeout, *, timing_metric="vision_wait_s", target=None):
    start = time.perf_counter()
    deadline = time.time() + timeout
    while time.time() < deadline:
        code = run(
            f"{docker_cmd} exec {DOCKER_CONTAINER} bash -lc "
            + shlex.quote(f"test -s {shlex.quote(VISION_OUTPUT_DOCKER)}"),
            check=False,
        )
        if code == 0:
            print("[AUTO] vision output is ready")
            elapsed = time.perf_counter() - start
            if timing_metric:
                fields = {}
                if target is not None:
                    fields["target"] = target
                print_timing(timing_metric, elapsed, **fields)
            return elapsed
        time.sleep(2.0)

    print(capture(f"{docker_cmd} exec {DOCKER_CONTAINER} bash -lc 'tail -80 /shared_data/vision_bridge.log'", check=False))
    raise TimeoutError(f"vision output not ready after {timeout} seconds")


def trigger_and_wait_vision(docker_cmd, target, timeout):
    start = time.perf_counter()
    trigger_vision(docker_cmd, target)
    wait_for_vision_output(docker_cmd, timeout, timing_metric=None, target=target)
    elapsed = time.perf_counter() - start
    print_timing("vision_wall_time_s", elapsed, target=target)
    return elapsed


def copy_vision_output(docker_cmd, host_path):
    host_path = Path(host_path)
    host_path.parent.mkdir(parents=True, exist_ok=True)
    run(f"{docker_cmd} cp {DOCKER_CONTAINER}:{VISION_OUTPUT_DOCKER} {shlex.quote(str(host_path))}")
    try:
        output = load_yaml(host_path)
        timing = output.get("timing", {})
        if "vision_compute_time_s" in timing:
            print_timing(
                "vision_compute_time_s",
                float(timing["vision_compute_time_s"]),
                target=output.get("target", ""),
                source=host_path.name,
            )
    except Exception as exc:
        print(f"[AUTO][WARN] could not read vision timing from {host_path}: {exc}")
    return host_path


def convert_vision_output(vision_path):
    vision_path = Path(vision_path)
    start = time.perf_counter()
    run(
        ros_bash(
            "ros2 run my_robot_vision vision_to_execution_yaml.py "
            f"--config {shlex.quote(str(BRIDGE_CONFIG))} "
            f"--plan {shlex.quote(str(PLAN_HOST))} "
            f"--vision {shlex.quote(str(vision_path))} "
            f"--output {shlex.quote(str(TASK_FILE))}"
        )
    )
    elapsed = time.perf_counter() - start
    print_timing("conversion_time_s", elapsed, vision_yaml=vision_path.name)
    print(capture(f"cat {shlex.quote(str(TASK_FILE))}"))
    return elapsed


def copy_and_convert_vision(docker_cmd):
    copy_vision_output(docker_cmd, VISION_OUTPUT_HOST)
    return convert_vision_output(VISION_OUTPUT_HOST)


def execute_pick_place(
    gripper_mode,
    dry_run,
    gripper_speed,
    gripper_force,
    gripper_wait,
    gripper_release_position,
    gripper_release_wait,
    movej_velocity,
    movej_acceleration,
    movel_velocity,
    movel_acceleration,
    pick_approach_movej_velocity,
    pick_approach_movel_velocity,
    pipeline_wait,
    return_home=True,
):
    if dry_run:
        print("[AUTO] dry-run enabled: not executing robot pick/place.")
        print_timing("robot_execution_time_s", 0.0, dry_run=True)
        return 0.0

    gripper_speed = max(0, min(255, int(gripper_speed)))
    gripper_force = max(0, min(255, int(gripper_force)))
    gripper_release_position = max(0, min(255, int(gripper_release_position)))
    return_home_text = "true" if return_home else "false"
    effective_pipeline_wait = float(pipeline_wait)
    if not dry_run and effective_pipeline_wait < MIN_ROBOT_PIPELINE_WAIT_S:
        print(
            "[AUTO][WARN] pipeline_wait too short for strict robot serialization; "
            f"using {MIN_ROBOT_PIPELINE_WAIT_S:.1f}s instead of {effective_pipeline_wait:.1f}s"
        )
        effective_pipeline_wait = MIN_ROBOT_PIPELINE_WAIT_S
    cmd = (
        "ros2 launch panda_pick run_ur5.launch.py "
        f"gripper_control_mode:={shlex.quote(gripper_mode)} "
        f"gripper_socket_speed:={gripper_speed} "
        f"gripper_socket_force:={gripper_force} "
        f"gripper_socket_open_wait_seconds:={float(gripper_wait):.3f} "
        f"gripper_socket_release_position:={gripper_release_position} "
        f"gripper_socket_release_wait_seconds:={float(gripper_release_wait):.3f} "
        f"gripper_urscript_wait_seconds:={float(gripper_wait):.3f} "
        f"task_file:={shlex.quote(str(TASK_FILE))} "
        "task_max_xy_offset:=0.15 "
        "task_max_z_offset:=0.15 "
        "task_max_descend:=0.30 "
        'urscript_pregrasp_joints:="$UR5_PREGRASP_JOINTS" '
        'urscript_preplace_joints:="$UR5_PREPLACE_JOINTS" '
        'urscript_home_joints:="$UR5_OBSERVE_JOINTS" '
        f"joint_ptp_return_home:={return_home_text} "
        f"urscript_movej_acceleration:={float(movej_acceleration):.3f} "
        f"urscript_movej_velocity:={float(movej_velocity):.3f} "
        f"urscript_pick_approach_movej_velocity:={float(pick_approach_movej_velocity):.3f} "
        f"urscript_movel_acceleration:={float(movel_acceleration):.3f} "
        f"urscript_movel_velocity:={float(movel_velocity):.3f} "
        f"urscript_pick_approach_movel_velocity:={float(pick_approach_movel_velocity):.3f} "
        "urscript_pick_lift_velocity:=0.14 "
        "urscript_descend_acceleration:=0.35 "
        "urscript_descend_velocity:=0.10 "
        "urscript_place_descend_velocity:=0.003 "
        "urscript_place_slow_final_descend:=0.020 "
        "urscript_place_settle_wait_seconds:=0.5 "
        f"urscript_pipeline_wait_seconds:={effective_pipeline_wait:.3f}"
    )
    start = time.perf_counter()
    output = capture(ros_bash(cmd))
    elapsed = time.perf_counter() - start
    print(output)
    failure_markers = (
        "process has died",
        "exit code 1",
        "超过安全限制",
        "[ERROR]",
    )
    if any(marker in output for marker in failure_markers):
        raise RuntimeError("robot execution launch reported an error; see log above")
    print_timing("robot_execution_time_s", elapsed, return_home=return_home_text)
    print("[AUTO] execution complete; URScript home pose is UR5_OBSERVE_JOINTS")
    return elapsed


def run_async_next_vision(args, rounds):
    """Overlap current robot execution with next-target perception.

    The vision Docker freezes the first observe RGB-D frame, so the next target
    is computed from the same observation while the wrist camera is moving.
    """
    if any("task" not in item for item in rounds):
        raise RuntimeError("--async-next-vision currently requires --product-yaml planner tasks")

    selected_tasks = [item["task"] for item in rounds]
    if not args.skip_observe:
        move_to_observe_pose()

    write_plan_tasks(selected_tasks)
    ensure_vision_service(args.docker_cmd, rounds[0]["target"], frozen_observation=True)

    cache_paths = {}
    first_target = rounds[0]["target"]
    print(f"\n[AUTO] async bootstrap vision target: {first_target}")
    trigger_and_wait_vision(args.docker_cmd, first_target, args.vision_timeout)
    cache_paths[0] = copy_vision_output(args.docker_cmd, vision_cache_path(0, first_target))

    for index, item in enumerate(rounds):
        target = item["target"]
        print(f"\n[AUTO] ===== async round {index + 1}/{len(rounds)} target: {target} =====")

        write_active_plan_task(item["task"])
        convert_vision_output(cache_paths[index])

        next_item = rounds[index + 1] if index + 1 < len(rounds) else None
        if next_item is not None:
            print(
                "[AUTO] starting next vision in Docker before current robot execution: "
                f"{next_item['target']}"
            )
            next_vision_trigger_time = time.perf_counter()
            trigger_vision(args.docker_cmd, next_item["target"])
        else:
            next_vision_trigger_time = None

        execute_pick_place(
            args.gripper_mode,
            args.dry_run,
            args.gripper_speed,
            args.gripper_force,
            args.gripper_wait,
            args.gripper_release_position,
            args.gripper_release_wait,
            args.movej_velocity,
            args.movej_acceleration,
            args.movel_velocity,
            args.movel_acceleration,
            args.pick_approach_movej_velocity,
            args.pick_approach_movel_velocity,
            args.pipeline_wait,
            False,
        )

        if next_item is not None:
            print(
                "[AUTO] waiting for next vision output after current execution "
                f"if it is not already ready: {next_item['target']}"
            )
            wait_after_execution = wait_for_vision_output(
                args.docker_cmd,
                args.vision_timeout,
                timing_metric="next_vision_wait_after_execution_s",
                target=next_item["target"],
            )
            if next_vision_trigger_time is not None:
                print_timing(
                    "next_vision_elapsed_since_trigger_s",
                    time.perf_counter() - next_vision_trigger_time,
                    target=next_item["target"],
                )
            print(
                "[AUTO][TIMING] "
                f"next_vision_ready_before_execution_done={str(wait_after_execution < 1.0).lower()} "
                f"target={shlex.quote(str(next_item['target']))}"
            )
            cache_paths[index + 1] = copy_vision_output(
                args.docker_cmd,
                vision_cache_path(index + 1, next_item["target"]),
            )


def parse_place(text):
    parts = [float(x.strip()) for x in text.split(",")]
    if len(parts) != 3:
        raise argparse.ArgumentTypeError("--place must be dx,dy,dz")
    return parts


def parse_places(text):
    if not text.strip():
        return []
    return [parse_place(item.strip()) for item in text.split(";") if item.strip()]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", default="yellow 2x4 brick.")
    parser.add_argument("--rounds", type=int, default=1,
                        help="repeat --target this many times when --targets is not provided")
    parser.add_argument("--targets", default="",
                        help="comma-separated targets for repeated rounds, e.g. 'yellow 2x4 brick.,red 2x2 brick.'")
    parser.add_argument("--place", type=parse_place, default=[0.0, 0.0, 0.0],
                        help="placement offset relative to assembly origin, meters: dx,dy,dz")
    parser.add_argument("--places", type=parse_places, default=[],
                        help="semicolon-separated placement offsets, one per target: '0,0,0;0.08,0,0'")
    parser.add_argument("--grasp-spin", type=float, default=0.0,
                        help="extra grasp yaw in degrees; use 90 or -90 for alternate grasp")
    parser.add_argument("--blueprint-yaw", type=float, default=0.0,
                        help="place yaw in radians, kept for compatibility with planner output")
    parser.add_argument("--docker-cmd", default="sudo docker")
    parser.add_argument("--vision-timeout", type=float, default=180.0)
    parser.add_argument("--skip-observe", action="store_true",
                        help="skip moving to the home/perception pose before vision")
    parser.add_argument("--async-next-vision", action="store_true",
                        help="compute the next target from the frozen observe frame while the robot executes the current task")
    parser.add_argument("--dry-run", action="store_true",
                        help="generate pick_place_task.yaml but do not execute robot")
    parser.add_argument("--gripper-mode", default="robotiq_socket",
                        choices=["none", "robotiq_socket", "urscript"])
    parser.add_argument("--gripper-speed", type=int, default=180,
                        help="Robotiq socket SPE value, 0-255")
    parser.add_argument("--gripper-force", type=int, default=80,
                        help="Robotiq socket FOR value, 0-255")
    parser.add_argument("--gripper-wait", type=float, default=4.0,
                        help="seconds to wait after each Robotiq open/close command")
    parser.add_argument("--gripper-release-position", type=int, default=140,
                        help="partial Robotiq POS after placing, before lifting; 255 is closed, 0 is fully open")
    parser.add_argument("--gripper-release-wait", type=float, default=0.5,
                        help="seconds to wait after the partial release command before lifting")
    parser.add_argument("--movej-velocity", type=float, default=0.60,
                        help="UR movej speed for large joint moves, including transfer from one placed block to the next task")
    parser.add_argument("--movej-acceleration", type=float, default=1.5,
                        help="UR movej acceleration for large joint moves")
    parser.add_argument("--movel-velocity", type=float, default=0.24,
                        help="UR movel speed for normal Cartesian moves; slow final place descent is controlled separately")
    parser.add_argument("--movel-acceleration", type=float, default=1.0,
                        help="UR movel acceleration for normal Cartesian moves")
    parser.add_argument("--pick-approach-movej-velocity", type=float, default=0.35,
                        help="UR movej speed from observation/current pose to the pick pregrasp joint pose")
    parser.add_argument("--pick-approach-movel-velocity", type=float, default=0.18,
                        help="UR movel speed from taught pregrasp to the vision-corrected pose above the object")
    parser.add_argument("--pipeline-wait", type=float, default=35.0,
                        help="host-side wait after publishing each URScript task; lower it to reduce idle time between tasks")
    parser.add_argument("--product-yaml", default="",
                        help="run myplanner.py on a final_product YAML and execute its generated sequence")
    parser.add_argument("--planner-output", default=str(PLAN_FROM_PRODUCT_HOST),
                        help="where to write the full plan generated from --product-yaml")
    parser.add_argument("--start-index", type=int, default=0,
                        help="first planner task index to execute when --product-yaml is used")
    parser.add_argument("--max-tasks", type=int, default=0,
                        help="limit number of planner tasks when --product-yaml is used; 0 means all")
    args = parser.parse_args()

    if not TAUGHT_ENV.exists():
        raise RuntimeError(f"missing taught joints file: {TAUGHT_ENV}")
    if args.rounds < 1:
        raise RuntimeError("--rounds must be at least 1")

    if args.product_yaml:
        product_yaml = Path(args.product_yaml).expanduser()
        if not product_yaml.is_absolute():
            product_yaml = REPO / product_yaml
        planner_output = Path(args.planner_output).expanduser()
        if not planner_output.is_absolute():
            planner_output = REPO / planner_output
        generate_product_plan(product_yaml, planner_output)
        planner_tasks = load_plan_tasks(planner_output)
        if args.start_index < 0 or args.start_index >= len(planner_tasks):
            raise RuntimeError(f"--start-index {args.start_index} is outside 0..{len(planner_tasks) - 1}")
        end_index = len(planner_tasks) if args.max_tasks <= 0 else min(len(planner_tasks), args.start_index + args.max_tasks)
        rounds = [{"target": task_target(task), "task": task} for task in planner_tasks[args.start_index:end_index]]
    else:
        targets = [item.strip() for item in args.targets.split(",") if item.strip()]
        if not targets:
            targets = [args.target] * args.rounds
        if args.places and len(args.places) < len(targets):
            raise RuntimeError(
                f"--places has {len(args.places)} item(s), but --targets/rounds needs {len(targets)}. "
                "Provide one place offset per target."
            )
        rounds = []
        for index, target in enumerate(targets):
            place = args.places[index] if args.places else args.place
            rounds.append({
                "target": target,
                "place": place,
                "grasp_spin": args.grasp_spin,
                "blueprint_yaw": args.blueprint_yaw,
            })

    if args.async_next_vision:
        run_async_next_vision(args, rounds)
        print("[AUTO] pipeline finished")
        return

    for index, item in enumerate(rounds, start=1):
        target = item["target"]
        print(f"\n[AUTO] ===== round {index}/{len(rounds)} target: {target} =====")
        if "task" in item:
            write_active_plan_task(item["task"])
        else:
            write_plan(target, item["place"], item["grasp_spin"], item["blueprint_yaw"])
        if not args.skip_observe:
            move_to_observe_pose()
        ensure_vision_service(args.docker_cmd, target)
        trigger_and_wait_vision(args.docker_cmd, target, args.vision_timeout)
        copy_and_convert_vision(args.docker_cmd)
        execute_pick_place(
            args.gripper_mode,
            args.dry_run,
            args.gripper_speed,
            args.gripper_force,
            args.gripper_wait,
            args.gripper_release_position,
            args.gripper_release_wait,
            args.movej_velocity,
            args.movej_acceleration,
            args.movel_velocity,
            args.movel_acceleration,
            args.pick_approach_movej_velocity,
            args.pick_approach_movel_velocity,
            args.pipeline_wait,
            True,
        )
        # The next round always starts by moving/confirming UR5_OBSERVE_JOINTS
        # before perception. The URScript execution also returns there after
        # each completed pick/place task.
    print("[AUTO] pipeline finished")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"[AUTO][ERROR] {exc}", file=sys.stderr)
        sys.exit(1)
