<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>o3p_node</name>
  <version>0.0.0</version>
  <description>ROS Node that uses the O3P API</description>
  <maintainer email="todo@todo.todo">todo</maintainer>
  <license>TODO: License declaration</license>

  <depend>pluginlib</depend>
  <depend>qtbase6-dev</depend>

  <!-- ROS1 -->
  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <depend condition="$ROS_VERSION == 1">roscpp</depend>
  <depend condition="$ROS_VERSION == 1">std_msgs</depend>
  <depend condition="$ROS_VERSION == 1">std_srvs</depend>
  <depend condition="$ROS_VERSION == 1">diagnostic_msgs</depend>
  <depend condition="$ROS_VERSION == 1">sensor_msgs</depend>
  <depend condition="$ROS_VERSION == 1">cv_bridge</depend>
  <depend>rviz</depend>

  <!-- ROS2 -->
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>
  <depend condition="$ROS_VERSION == 2">rclcpp</depend>
  <depend condition="$ROS_VERSION == 2">std_msgs</depend>
  <depend condition="$ROS_VERSION == 2">std_srvs</depend>
  <depend condition="$ROS_VERSION == 2">diagnostic_msgs</depend>
  <depend condition="$ROS_VERSION == 2">sensor_msgs</depend>
  <depend condition="$ROS_VERSION == 2">cv_bridge</depend>
  <depend condition="$ROS_VERSION == 2">rviz2</depend>
  <depend condition="$ROS_VERSION == 2">rviz_common</depend>
  <depend condition="$ROS_VERSION == 2">rviz_rendering</depend>
  <!-- Add TF dependencies -->
  <depend condition="$ROS_VERSION == 2">tf2_ros</depend>
  <depend condition="$ROS_VERSION == 2">geometry_msgs</depend>

  <exec_depend condition="$ROS_VERSION == 2">ros-humble-rviz2</exec_depend>

  <export>
    <rviz plugin="${prefix}/rviz_common_plugins.xml" />
    <!-- Export for ROS1 -->
    <build_type condition="$ROS_VERSION == 1">catkin</build_type>
    <!-- Export for ROS2 -->
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
  </export>
</package>
